#
# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
# Copyright 2023-2025, Hesham Almatary (hesham.almatary@cl.cam.ac.uk)
#
# SPDX-License-Identifier: GPL-2.0-only
#

cmake_minimum_required(VERSION 3.7.2)

declare_platform(morello-qemu KernelPlatformMorelloQEMU PLAT_MORELLO_QEMU KernelSel4ArchAarch64)

if(KernelPlatformMorelloQEMU)
    set(QEMU_ARCH "morello")
    declare_seL4_arch(aarch64)
    set(KernelArchArmV8a ON)
    set(KernelArmCpuMorello ON)

    # This DTS was generated by the following command:
    # qemu-system-morello -machine virt,gic-version=2 -cpu morello -nographic  -m size=2048  -kernel sel4.elf
    list(APPEND KernelDTSList "tools/dts/morello-qemu-gicv2.dts")
    list(APPEND KernelDTSList "src/plat/morello-qemu/overlay-morello-qemu.dts")

    if(KernelArmHypervisorSupport)
        list(APPEND KernelDTSList "${CMAKE_CURRENT_LIST_DIR}/overlay-reserve-vm-memory.dts")
    endif()

    declare_default_headers(
        TIMER_FREQUENCY 62500000
        MAX_IRQ 159
        NUM_PPI 32
        TIMER drivers/timer/arm_generic.h
        INTERRUPT_CONTROLLER arch/machine/gic_v2.h
        CLK_MAGIC 4611686019llu
        CLK_SHIFT 58u
        KERNEL_WCET 10u
    )

endif()

add_sources(
    DEP "KernelPlatformMorelloQEMU"
    CFILES src/arch/arm/machine/l2c_nop.c src/arch/arm/machine/gic_v2.c
)
