# Copyright 2021, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

# sel4exercises runs

name: seL4Exercises

on:
  pull_request:
    paths-ignore:
      - 'manual/**'
      - 'LICENSES/**'
      - '*.md'
  workflow_dispatch:

jobs:
  exercises:
    name: Exercises
    uses: The-Capable-Hub/CHERI-seL4-ci-actions/.github/workflows/sel4exercises.yml@michaelcobb/capable-hub-ci
    with:
      runner: the-capable-hub-aws-ci
      container-image: trustworthysystems/sel4:latest
